= iOS - Swift
Creado por Rodrigo Francisco <rhodfra@gmail.com>
Version 1.0, 12.03.2021
//:keywords: 
//:sectnums: 
// Configuracion de la tabla de contenidos
:toc: 
:toc-placement!:
:toclevels: 4                                          
:toc-title: Contenido

// Ruta base de las imagenes
:imagesdir: ./README.assets/ 

// Resaltar sintaxis
:source-highlighter: pygments

// Iconos para entorno local
ifndef::env-github[:icons: font]

// Iconos para entorno github
ifdef::env-github[]
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

toc::[]

Apuntes de mi aprendizaje con `swift`

== Particularidades del lenguaje

A continuación se describen algunas características interesantes de  _Swift_,
probablemente esta sección se reorganize posteriormente.

=== Estructuras y clases

En `swift` las estructuras y las clases son muy cercanas en muchos aspectos con
comparación con otros lenguajes de programación.

Las diferencias entre las clases y loas estructuras es que *las clases tienen*:

* La herencia permite que una clase herede las características de otra.
* La conversión de tipos le permite verificar e interpretar el tipo de una
instancia de clase en tiempo de ejecución.
* Los desinicializadores (_deinitializers_) permiten que una instancia de una
clase libere cualquier recurso que haya asignado.
//* El recuento de referencias permite más de una referencia a una instancia de
//clase.

Otras diferencias _importantes_:

* Las *estructuras* y las _enumeraciones_ son _value type_ (valores por tipo).
Si las pasamos como parámetro de una función o las asignamos a otras variables
se creará una copia.
* Las *clases* son _reference type_ (tipos por referencia).


*Sintaxis básica*


[source,swift]
----
struct SomeStructure {
    // structure definition goes here
}
class SomeClass {
    // class definition goes here
}
----

==== Inicializadores de miembro (Memberwise initializers)

Las *estructuras* simepre tiene asignado de manera automática un inicializador
por defecto.


[source,swift]
----
let vga = Resolution(width: 640, height: 480)
----

[NOTE]
====
Las colecciones definidas en la librería estándar como arreglos, diccionarios y
cadenas usan una optimización para reducir costo computacional de copiar toda la
colección.
La copia no se hace inmediatamente. Se hace al momento de que se quiere
modificar alguno de los elementos de la copia.
====

==== Identity operator

Para identificar si una variable o una constante hace referencia a una misma
instancia de una _clase_ se utilizan los siguientes operadores:

* `===` (operador identical)
* `!==` (operador not idential)

=== Properties

Para la *estructuras*, al ser _value types_, cuando se crean una instancia y se
asigna como _constante_. TODAS sus propiedades se marcan como constantes.

[source,swift]
----
let rangeOfFourItems = FixedLengthRange(firstValue: 0, length: 4)
// this range represents integer values 0, 1, 2, and 3
rangeOfFourItems.firstValue = 6
// this will report an error, even though firstValue is a variable property
----

Las *clases* son _reference types_, al crear una instancia como _constante_ se
pueden seguir modificando las propiedades.

==== Lazy properties

Una propiedad almacenada de forma peresoza (_lazy_) es aquella cuyo valor inical
no se calcula hasta la primera vez que se utiliza.

.Se usan principalmente cuando:
* El valor de la propiedad depende de factores externos que no son conocidos en
el momento
* Son útiles para cuando la propiedad se obtenga de calculos computacionalmente
complejos y no se deban realizar a menos que se necesiten.


[source,swift]
----
class DataImporter {
    /*
    DataImporter is a class to import data from an external file.
    The class is assumed to take a nontrivial amount of time to initialize.
    */
    var filename = "data.txt"
    // the DataImporter class would provide data importing functionality here
}

class DataManager {
    lazy var importer = DataImporter()
    var data = [String]()
    // the DataManager class would provide data management functionality here
}

let manager = DataManager()
manager.data.append("Some data")
manager.data.append("Some more data")
// the DataImporter instance for the importer property hasn't yet been created
----

==== Computed properties

Las propiedades calculadas (computed) no almacenan valores sino que: _proveen un
*getter*_ y 

* OPCIONALMENTE un *setter* para recuperar los y asignar los valores de
otras propiedades de manera indirecta.
* Si una _computed property_ carece de *setter* se conoce como _red only
computed property_

.Se pueden usar en 
* clases, 
* estructuras y 
* enumeraciones

_Understand by example_


[source,swift]
----
struct Point {
  var x = 0.0, y = 0.0
}
struct Size {
  var width = 0.0, height = 0.0
}
struct Rect {
  var origin = Point()
  var size = Size()
  var center: Point {
    get {
      let centerX = origin.x + (size.width / 2)
      let centerY = origin.y + (size.height / 2)
      return Point(x: centerX, y: centerY)
    }
    set(newCenter) {
      origin.x = newCenter.x - (size.width / 2)
      origin.y = newCenter.y - (size.height / 2)
    }
  }
}
var square = Rect(origin: Point(x: 0.0, y: 0.0),
              size: Size(width: 10.0, height: 10.0))
let initialSquareCenter = square.center
square.center = Point(x: 15.0, y: 15.0)
print("square.origin is now at (\(square.origin.x), \(square.origin.y))")
// Prints "square.origin is now at (10.0, 10.0)"
----

===== Una manera más corta de declarar un SETTER y un getter


[source,]
----
struct AlternativeRect {
  var origin = Point()
  var size = Size()
  var center: Point {
    get {
      Point(x: origin.x + (size.width / 2),
          y: origin.y + (size.height / 2))
    }
    set {
      origin.x = newValue.x - (size.width / 2) //<1>
        origin.y = newValue.y - (size.height / 2)
    }
  }
}
----
<1> `newValue` es el nombre el argumento de `set` si es que se específica
explícitamente.

===== Shorthand para Read-Only computed properties

[source,]
----
struct Cuboid {
  var width = 0.0, height = 0.0, depth = 0.0
    var volume: Double {
      return width * height * depth //<1>
    }
}
----
<1> No se requiere de la palabra `get`
